// This file exports the conversation preset object used in the Conversation and Preset schemas.
export const conversationPreset = {
    endpoint: { type: String, default: null, required: true },
    endpointType: { type: String },
    model: { type: String, required: false },
    region: { type: String, required: false },
    chatGptLabel: { type: String, required: false },
    examples: { type: [{ type: Object }], default: undefined },
    modelLabel: { type: String, required: false },
    promptPrefix: { type: String, required: false },
    temperature: { type: Number, required: false },
    top_p: { type: Number, required: false },
    topP: { type: Number, required: false },
    topK: { type: Number, required: false },
    maxOutputTokens: { type: Number, required: false },
    presence_penalty: { type: Number, required: false },
    frequency_penalty: { type: Number, required: false },
    file_ids: { type: [{ type: String }], default: undefined },
    resendImages: { type: Boolean },
    promptCache: { type: Boolean },
    thinking: { type: Boolean },
    thinkingBudget: { type: Number },
    system: { type: String },
    resendFiles: { type: Boolean },
    imageDetail: { type: String },
    agent_id: { type: String },
    assistant_id: { type: String },
    instructions: { type: String },
    stop: { type: [{ type: String }], default: undefined },
    isArchived: { type: Boolean, default: false },
    iconURL: { type: String },
    greeting: { type: String },
    spec: { type: String },
    tags: { type: [String], default: [] },
    tools: { type: [{ type: String }], default: undefined },
    maxContextTokens: { type: Number },
    max_tokens: { type: Number },
    reasoning_effort: { type: String },
};