name: CI & Code Quality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code with ESLint
        run: npm run lint --if-present

      - name: TypeScript build (compile)
        run: npm run build --if-present

      - name: Run tests
        run: npm run test --if-present

  static_analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and save results in SARIF
        id: eslint
        run: |
          npx eslint . --ext .ts --config eslint.config.mjs --format @microsoft/eslint-formatter-sarif --output-file eslint_results.sarif || true

      - name: Run depcheck and save results
        id: depcheck
        run: |
          npx depcheck > depcheck_results.txt || true

      - name: Run ts-prune and save results
        id: tsprune
        run: |
          npx ts-prune > tsprune_results.txt || true

      - name: Upload Code Quality Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-results
          path: |
            eslint_results.sarif
            depcheck_results.txt
            tsprune_results.txt